import Link from "next/link";

const insights = [
  {
    title: "Your highest-risk window is Thursday 5-7 PM",
    body: "8 of your last 12 high-intensity cravings happened in this window, right after work. WAVE will fire a prophylactic notification at 4:45 PM each Thursday.",
    tag: "Time pattern",
  },
  {
    title: "Your medication reduces craving intensity by ~2.7 points",
    body: "Sessions on medication days start at an average of 5.1/10. Sessions on missed-dose days start at 7.8/10. That delta is visible in your own data.",
    tag: "Medication correlation",
  },
  {
    title: "Stress is your most common trigger",
    body: "Stress and emotions accounted for 8 of your last 12 sessions. This might be worth raising with your counselor next visit.",
    tag: "Trigger pattern",
  },
  {
    title: "You surf better in the evening",
    body: "Your average intensity drop is 5.2 points after 6 PM versus 3.1 in the morning. You might be tired but your nervous system is with you.",
    tag: "Performance pattern",
  },
];

export default function InsightsPage() {
  return (
    <section className="mx-auto max-w-4xl px-6 py-16">
      <nav aria-label="Breadcrumb" className="text-sm text-foreground/60">
        <Link href="/" className="hover:text-accent">
          Home
        </Link>
        <span className="mx-2">/</span>
        <span>Insights</span>
      </nav>

      <h1 className="mt-4 text-3xl font-semibold tracking-tight">
        What Gemma noticed this week
      </h1>
      <p className="mt-2 text-foreground/70">
        WAVE reviews your session history locally and surfaces one actionable
        pattern at a time. None of this leaves your device.
      </p>

      <ul className="mt-10 space-y-4">
        {insights.map((insight) => (
          <li
            key={insight.title}
            className="rounded-2xl border border-border bg-surface p-6"
          >
            <div className="flex items-center gap-2 text-xs uppercase tracking-wide text-accent">
              <span className="h-1.5 w-1.5 rounded-full bg-accent" />
              {insight.tag}
            </div>
            <h2 className="mt-2 text-lg font-semibold">{insight.title}</h2>
            <p className="mt-2 text-sm text-foreground/70 leading-relaxed">
              {insight.body}
            </p>
          </li>
        ))}
      </ul>

      <aside className="mt-10 rounded-2xl border border-border bg-surface-muted p-6 text-sm text-foreground/70">
        <p>
          These insights are generated by an on-device language model (Gemma 4
          in production, Claude via a Route Handler in the hackathon demo).
          They are descriptive, not prescriptive — WAVE does not tell you to
          start, stop, or change medication. That conversation belongs with
          your prescriber.
        </p>
      </aside>

      <div className="mt-10 flex items-center justify-between">
        <Link
          href="/history"
          className="text-sm text-foreground/60 hover:text-accent"
        >
          ← Back to history
        </Link>
        <Link
          href="/session"
          className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-accent-foreground font-medium hover:opacity-90"
        >
          Start another session →
        </Link>
      </div>
    </section>
  );
}
