"use client";

import { useState } from "react";
import Link from "next/link";

import {
  MOCK_SESSIONS,
  STATIC_INSIGHTS,
  type InsightCard,
} from "@/lib/data/mock-sessions";
import type { InsightsPayload } from "@/lib/prompts/schemas";

type Status = "idle" | "loading" | "error";

export default function InsightsPage() {
  const [cards, setCards] = useState<InsightCard[]>(STATIC_INSIGHTS);
  const [status, setStatus] = useState<Status>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function handleRegenerate() {
    setStatus("loading");
    setErrorMessage(null);
    try {
      const res = await fetch("/api/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sessions: MOCK_SESSIONS }),
      });

      if (!res.ok) {
        const detail = (await res.json().catch(() => null)) as
          | { error?: string; message?: string }
          | null;
        throw new Error(
          detail?.message ?? detail?.error ?? `Request failed (${res.status})`,
        );
      }

      const data = (await res.json()) as InsightsPayload;
      setCards(data.insights);
      setStatus("idle");
    } catch (err) {
      setErrorMessage((err as Error).message);
      setStatus("error");
    }
  }

  const isLoading = status === "loading";

  return (
    <section className="mx-auto max-w-4xl px-6 py-16">
      <nav aria-label="Breadcrumb" className="text-sm text-foreground/60">
        <Link href="/" className="hover:text-accent">
          Home
        </Link>
        <span className="mx-2">/</span>
        <span>Insights</span>
      </nav>

      <div className="mt-4 flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">
            What Gemma noticed this week
          </h1>
          <p className="mt-2 text-foreground/70">
            WAVE reviews your session history locally and surfaces one
            actionable pattern at a time. None of this leaves your device.
          </p>
        </div>
        <button
          type="button"
          onClick={handleRegenerate}
          disabled={isLoading}
          className="inline-flex items-center gap-2 rounded-full bg-accent px-4 py-2 text-sm font-medium text-accent-foreground hover:opacity-90 transition disabled:opacity-50"
          aria-busy={isLoading}
        >
          {isLoading ? (
            <>
              <span
                aria-hidden
                className="h-3 w-3 animate-spin rounded-full border-2 border-accent-foreground/40 border-t-accent-foreground"
              />
              Regenerating…
            </>
          ) : (
            "Regenerate report"
          )}
        </button>
      </div>

      {status === "error" ? (
        <div
          role="alert"
          className="mt-6 rounded-2xl border border-danger/40 bg-danger-soft p-4 text-sm text-danger"
        >
          <p className="font-medium">Couldn&apos;t regenerate insights.</p>
          <p className="mt-1 text-danger/80">{errorMessage}</p>
          <button
            type="button"
            onClick={handleRegenerate}
            className="mt-3 rounded-full border border-danger/40 bg-surface px-3 py-1 text-xs font-medium text-danger hover:bg-danger-soft transition"
          >
            Retry
          </button>
        </div>
      ) : null}

      <ul className="mt-10 space-y-4" aria-busy={isLoading}>
        {cards.map((insight) => (
          <li
            key={`${insight.tag}-${insight.title}`}
            className="rounded-2xl border border-border bg-surface p-6"
          >
            <div className="flex items-center gap-2 text-xs uppercase tracking-wide text-accent">
              <span className="h-1.5 w-1.5 rounded-full bg-accent" />
              {insight.tag}
            </div>
            <h2 className="mt-2 text-lg font-semibold">{insight.title}</h2>
            <p className="mt-2 text-sm text-foreground/70 leading-relaxed">
              {insight.body}
            </p>
          </li>
        ))}
      </ul>

      <aside className="mt-10 rounded-2xl border border-border bg-surface-muted p-6 text-sm text-foreground/70">
        <p>
          These insights are generated by Gemma 4 E2B running on your device —
          in the browser via WebGPU in the web demo, and via LiteRT on mobile.
          They are descriptive, not prescriptive — WAVE does not tell you to
          start, stop, or change medication. That conversation belongs with
          your prescriber.
        </p>
      </aside>

      <div className="mt-10 flex items-center justify-between">
        <Link
          href="/history"
          className="text-sm text-foreground/60 hover:text-accent"
        >
          ← Back to history
        </Link>
        <Link
          href="/session"
          className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-accent-foreground font-medium hover:opacity-90"
        >
          Start another session →
        </Link>
      </div>
    </section>
  );
}
