// Insights — RN port of client/app/insights/page.tsx. Renders the
// STATIC_INSIGHTS card stack and offers a "Regenerate" button that
// calls generateInsights(MOCK_SESSIONS) through the local Gemma
// runtime. The regenerate flow, error handling, and model wiring are
// unchanged — only the presentation is re-skinned to dark oceanic.

import { useState } from "react";
import { Link } from "expo-router";
import {
  ActivityIndicator,
  Pressable,
  StyleSheet,
  Text,
  View,
} from "react-native";

import {
  Display,
  Eyebrow,
  Lede,
  TopBar,
  WaveCard,
  WaveScreen,
} from "@/components/wave-ui";
import { WaveColors, WaveType } from "@/constants/wave-theme";
import { generateInsights } from "@/gemma/insights";
import {
  MOCK_SESSIONS,
  STATIC_INSIGHTS,
  type InsightCard,
} from "@/data/mock-sessions";

type Status = "idle" | "loading" | "error";

export default function InsightsScreen() {
  const [cards, setCards] = useState<InsightCard[]>(STATIC_INSIGHTS);
  const [status, setStatus] = useState<Status>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function handleRegenerate() {
    setStatus("loading");
    setErrorMessage(null);
    try {
      const payload = await generateInsights(MOCK_SESSIONS);
      setCards(payload.insights);
      setStatus("idle");
    } catch (err) {
      setErrorMessage((err as Error).message);
      setStatus("error");
    }
  }

  const isLoading = status === "loading";

  return (
    <WaveScreen>
      <TopBar crumb="Insights" />

      <Eyebrow accent>On-device review</Eyebrow>
      <Display>What WAVE noticed{"\n"}this week.</Display>
      <Lede>
        WAVE reviews your session history locally and surfaces one actionable
        pattern at a time. None of this leaves your device.
      </Lede>

      <Pressable
        onPress={handleRegenerate}
        disabled={isLoading}
        accessibilityState={{ busy: isLoading }}
        style={({ pressed }) => [
          styles.regenButton,
          pressed && !isLoading && styles.regenPressed,
          isLoading && styles.regenDisabled,
        ]}
      >
        {isLoading ? (
          <View style={styles.regenRow}>
            <ActivityIndicator size="small" color={WaveColors.waveCrest} />
            <Text style={styles.regenText}>Regenerating…</Text>
          </View>
        ) : (
          <Text style={styles.regenText}>Regenerate report</Text>
        )}
      </Pressable>

      {status === "error" ? (
        <WaveCard style={styles.errorPanel}>
          <Text style={styles.errorTitle}>Couldn&apos;t regenerate insights.</Text>
          {errorMessage ? (
            <Text style={styles.errorBody}>{errorMessage}</Text>
          ) : null}
          <Pressable style={styles.errorRetry} onPress={handleRegenerate}>
            <Text style={styles.errorRetryText}>Retry</Text>
          </Pressable>
        </WaveCard>
      ) : null}

      <View style={[styles.cardList, isLoading && styles.cardListBusy]}>
        {cards.map((insight) => (
          <WaveCard key={`${insight.tag}-${insight.title}`}>
            <View style={styles.tagRow}>
              <View style={styles.tagDot} />
              <Eyebrow accent>{insight.tag}</Eyebrow>
            </View>
            <Text style={styles.cardTitle}>{insight.title}</Text>
            <Text style={styles.cardBody}>{insight.body}</Text>
          </WaveCard>
        ))}
      </View>

      <WaveCard>
        <Text style={styles.asideBody}>
          These insights are generated by Gemma 4 E2B running on your device —
          via LiteRT on mobile. They are descriptive, not prescriptive — WAVE
          does not tell you to start, stop, or change medication. That
          conversation belongs with your prescriber.
        </Text>
      </WaveCard>

      <View style={styles.footer}>
        <Link href="/history" asChild>
          <Text style={styles.footerLink}>← Back to history</Text>
        </Link>
        <Link href="/session/intake" asChild>
          <Text style={styles.footerLinkAccent}>Start another session →</Text>
        </Link>
      </View>
    </WaveScreen>
  );
}

const styles = StyleSheet.create({
  regenButton: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: WaveColors.borderGlow,
    backgroundColor: "rgba(232, 243, 252, 0.05)",
    paddingVertical: 12,
    paddingHorizontal: 26,
  },
  regenPressed: { backgroundColor: WaveColors.chipActive },
  regenDisabled: { opacity: 0.4 },
  regenRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  regenText: {
    color: WaveColors.ink,
    fontSize: 16,
    fontFamily: WaveType.serif,
    fontStyle: "italic",
  },
  errorPanel: {
    backgroundColor: WaveColors.dangerSoft,
    borderColor: "rgba(248, 113, 113, 0.4)",
    gap: 4,
  },
  errorTitle: { color: WaveColors.danger, fontWeight: "600", fontSize: 13 },
  errorBody: { color: "rgba(248, 113, 113, 0.85)", fontSize: 12 },
  errorRetry: {
    alignSelf: "flex-start",
    marginTop: 6,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.4)",
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  errorRetryText: { color: WaveColors.danger, fontSize: 11, fontWeight: "600" },
  cardList: { gap: 10 },
  cardListBusy: { opacity: 0.55 },
  tagRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  tagDot: {
    width: 5,
    height: 5,
    borderRadius: 5,
    backgroundColor: WaveColors.waveGlow,
  },
  cardTitle: {
    color: WaveColors.ink,
    fontSize: 19,
    fontFamily: WaveType.serif,
    fontStyle: "italic",
    letterSpacing: -0.3,
  },
  cardBody: {
    color: WaveColors.inkMute,
    fontSize: 13,
    lineHeight: 20,
    fontFamily: WaveType.sans,
  },
  asideBody: {
    color: WaveColors.inkFaint,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: WaveType.sans,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    gap: 8,
    flexWrap: "wrap",
  },
  footerLink: {
    color: WaveColors.inkFaint,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: WaveType.mono,
  },
  footerLinkAccent: {
    color: WaveColors.waveGlow,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: WaveType.mono,
  },
});
