// Insights — RN port of client/app/insights/page.tsx. Renders the
// STATIC_INSIGHTS card stack and offers a "Regenerate" button that
// calls generateInsights(MOCK_SESSIONS) through the local Gemma
// runtime (src/runtime/litert-generators.ts).
//
// The web counterpart wraps this surface in a ModelPreloadGate layout
// that warms the wllama model before rendering. On mobile the model
// is downloaded lazily through the LiteRT smoke flow; we keep this
// screen renderable without that warm-up and surface any runtime
// failure inline via the error banner.

import { useState } from "react";
import { Link } from "expo-router";
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";

import { generateInsights } from "@/gemma/insights";
import {
  MOCK_SESSIONS,
  STATIC_INSIGHTS,
  type InsightCard,
} from "@/data/mock-sessions";

const ACCENT = "#6366F1";
const DANGER = "#F87171";

type Status = "idle" | "loading" | "error";

export default function InsightsScreen() {
  const [cards, setCards] = useState<InsightCard[]>(STATIC_INSIGHTS);
  const [status, setStatus] = useState<Status>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function handleRegenerate() {
    setStatus("loading");
    setErrorMessage(null);
    try {
      const payload = await generateInsights(MOCK_SESSIONS);
      setCards(payload.insights);
      setStatus("idle");
    } catch (err) {
      setErrorMessage((err as Error).message);
      setStatus("error");
    }
  }

  const isLoading = status === "loading";

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
      contentInsetAdjustmentBehavior="automatic"
    >
      <Text style={styles.title}>What Gemma noticed this week</Text>
      <Text style={styles.subtitle}>
        WAVE reviews your session history locally and surfaces one actionable
        pattern at a time. None of this leaves your device.
      </Text>

      <Pressable
        onPress={handleRegenerate}
        disabled={isLoading}
        style={[styles.regenButton, isLoading && styles.regenButtonDisabled]}
        accessibilityState={{ busy: isLoading }}
      >
        {isLoading ? (
          <View style={styles.regenButtonRow}>
            <ActivityIndicator size="small" color="#F1F1F4" />
            <Text style={styles.regenButtonText}>Regenerating…</Text>
          </View>
        ) : (
          <Text style={styles.regenButtonText}>Regenerate report</Text>
        )}
      </Pressable>

      {status === "error" ? (
        <View style={styles.errorPanel} accessibilityRole="alert">
          <Text style={styles.errorTitle}>Couldn&apos;t regenerate insights.</Text>
          {errorMessage ? (
            <Text style={styles.errorBody}>{errorMessage}</Text>
          ) : null}
          <Pressable style={styles.errorRetry} onPress={handleRegenerate}>
            <Text style={styles.errorRetryText}>Retry</Text>
          </Pressable>
        </View>
      ) : null}

      <View style={[styles.cardList, isLoading && styles.cardListBusy]}>
        {cards.map((insight) => (
          <View
            key={`${insight.tag}-${insight.title}`}
            style={styles.card}
          >
            <View style={styles.cardTagRow}>
              <View style={styles.cardTagDot} />
              <Text style={styles.cardTag}>{insight.tag}</Text>
            </View>
            <Text style={styles.cardTitle}>{insight.title}</Text>
            <Text style={styles.cardBody}>{insight.body}</Text>
          </View>
        ))}
      </View>

      <View style={styles.aside}>
        <Text style={styles.asideBody}>
          These insights are generated by Gemma 4 E2B running on your device —
          via LiteRT on mobile. They are descriptive, not prescriptive — WAVE
          does not tell you to start, stop, or change medication. That
          conversation belongs with your prescriber.
        </Text>
      </View>

      <View style={styles.footer}>
        <Link href="/history" asChild>
          <Pressable hitSlop={8}>
            <Text style={styles.footerLink}>← Back to history</Text>
          </Pressable>
        </Link>
        <Link href="/session/intake" asChild>
          <Pressable style={styles.primaryButton}>
            <Text style={styles.primaryButtonText}>Start another session →</Text>
          </Pressable>
        </Link>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#08080C" },
  content: { padding: 16, gap: 14, paddingBottom: 48 },
  title: { color: "#F1F1F4", fontSize: 22, fontWeight: "700" },
  subtitle: { color: "#9CA3AF", fontSize: 13, lineHeight: 19 },
  regenButton: {
    alignSelf: "flex-start",
    backgroundColor: ACCENT,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  regenButtonDisabled: { opacity: 0.5 },
  regenButtonRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  regenButtonText: { color: "#F1F1F4", fontWeight: "600", fontSize: 13 },
  errorPanel: {
    backgroundColor: "rgba(248, 113, 113, 0.1)",
    borderColor: "rgba(248, 113, 113, 0.4)",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 4,
  },
  errorTitle: { color: DANGER, fontWeight: "600", fontSize: 13 },
  errorBody: { color: "rgba(248, 113, 113, 0.85)", fontSize: 12 },
  errorRetry: {
    alignSelf: "flex-start",
    marginTop: 6,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.4)",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: "#16161F",
  },
  errorRetryText: { color: DANGER, fontSize: 11, fontWeight: "600" },
  cardList: { gap: 10 },
  cardListBusy: { opacity: 0.6 },
  card: {
    backgroundColor: "#16161F",
    borderRadius: 12,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: "#23232F",
    padding: 14,
    gap: 6,
  },
  cardTagRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  cardTagDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: ACCENT,
  },
  cardTag: {
    color: ACCENT,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  cardTitle: { color: "#F1F1F4", fontSize: 15, fontWeight: "600" },
  cardBody: { color: "#9CA3AF", fontSize: 13, lineHeight: 19 },
  aside: {
    backgroundColor: "#1C1C28",
    borderRadius: 12,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: "#23232F",
    padding: 14,
  },
  asideBody: { color: "#9CA3AF", fontSize: 12, lineHeight: 18 },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    gap: 8,
    flexWrap: "wrap",
  },
  footerLink: { color: "#9CA3AF", fontSize: 13 },
  primaryButton: {
    backgroundColor: ACCENT,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  primaryButtonText: { color: "#F1F1F4", fontWeight: "600", fontSize: 13 },
});
